version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql_server_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=JasonRocks10
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "JasonRocks10", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s

volumes:
  mssql_data:
